---
kind: pipeline
type: docker
name: ci
trigger:
  event:
    - push
    - pull_request
steps:
  - name: test
    image: node:21-alpine
    commands:
      - yarn install
      - yarn test

---
kind: pipeline
type: exec
name: on-host
trigger:
  event:
    - push
    - pull_request
depends_on:
  - ci
steps:
  - name: build
    when:
      branch:
        - main
    environment:
      CI_DEPLOY_PWD:
        from_secret: CI_DEPLOY_PWD
    commands:
      - cd $CI_DEPLOY_PWD
      - ./deploy.sh
---
kind: pipeline
type: exec
name: trending
trigger:
  event:
    - cron
    - custom
  cron:
    include:
      - trending
steps:
  - name: call
    environment:
      CI_API_SECRET:
        from_secret: CI_API_SECRET
    commands:
      - curl -X POST "https://masto.kukei.eu/api/trends?s=$${CI_API_SECRET}"

---
kind: signature
hmac: c59e929bf076fe89cc8bce7c1e656d83fb9f58e3c0f6bf73d51dd97f3e9beb9e

...
