---
kind: pipeline
type: docker
name: ci
trigger:
  event:
    - push
steps:
  - name: test
    image: node:21-alpine
    commands:
      - yarn install
      - yarn test

---
kind: pipeline
type: exec
name: on-host
depends_on:
  - ci
steps:
  - name: build
    when:
      branch:
        - main
    environment:
      CI_DEPLOY_PWD:
        from_secret: CI_DEPLOY_PWD
    commands:
      - cd $CI_DEPLOY_PWD
      - ./deploy.sh
---
kind: pipeline
type: exec
name: trending
trigger:
  event:
    - cron
    - custom
  cron:
    include:
      - 0 0 /2 * * *
steps:
  - name: call
    environment:
      CI_API_SECRET:
        from_secret: CI_API_SECRET
    commands:
      - curl -X POST "https://masto.kukei.eu/api/trends?s=$CI_API_SECRET"

---
kind: signature
hmac: 4735cdfc64c2e6427d410803970477b768d25663c4e86cd891da9e64d06e47f2

...
