version: '3'
services:
  masto-kukei-web:
    build: .
    command: yarn start
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
  masto-kukei-llm:
    build: .
    command: yarn llm
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
