export const instanceHosts = [
	'social.nowicki.io',
	'pol.social',
	'101010.pl',
	'mastodon.social',
	'mastodon.online',
	'fosstodon.org',
	'gruene.social',
	'hachyderm.io',
	'troet.cafe',
	'mastodon.art',
	'ioc.exchange',
	'nrw.social',
	'norden.social',
	'sueden.social',
	'social.cologne',
	// Nope, auth only
	// 'social.linux.pizza',
	'muenchen.social',
	'ruhr.social',
	'hessen.social',
	'chaos.social',
	'lewacki.space',
	'mas.to',
	'social.vivaldi.net',
	'front-end.social',
	'ard.social',
	'zdf.social',
	'edi.social',
]
