when:
    - event: push
      branch: main

depends_on:
    - test

labels:
    backend: local

steps:
    - name: deploy
      image: bash
      commands:
          - cd /home/sznowicki/storage/kukei-masto
          - ./deploy.sh
