when:
    - event: push
      branch: main

depends_on:
    - test

labels:
    backend: local

steps:
    - name: deploy
      image: bash
      commands:
          - cd /mnt/serverstorage/servers/
          - ./deploy.sh
