when:
    - event: cron
      cron: trending

labels:
    backend: local

steps:
    - name: trigger
      image: bash
      environment:
          MASTO_BOT_INCOMING_SECRET:
                from_secret: MASTO_BOT_INCOMING_SECRET
      commands:
          - curl -o - -X POST "https://masto.kukei.eu/api/summaries?s=$${MASTO_BOT_INCOMING_SECRET}"
